### ISSUE TITLE
Fix colsample_bynode

### ISSUE THREAD

**Issue by lorentzenchr** [lorentzenchr/notebooks#4]
In the new blog post with code
- https://github.com/lorentzenchr/notebooks/blob/master/blogposts/2021-11-13%20random%20forests%20monotone.ipynb
- https://github.com/lorentzenchr/notebooks/blob/master/blogposts/2021-11-13%20random%20forests%20monotone.r

the formula for `colsample_bynode` might need correction.
Python `int(np.sqrt(m)) / m` -> `np.sqrt(m) // m`
R `floor(sqrt(m)) / m` -> `floor(sqrt(m) / m)`

@mayer79 ping

**Comment by mayer79** [comment]
Ja, das ist etwas seltsam, danke. Ich setze den Wert auf 1/3 und aktualisiere alles. Gesendet von Mail für Windows Von: Christian LorentzenGesendet: Samstag, 13. November 2021 14:38An: lorentzenchr/notebooksCc: Michael Mayer; MentionBetreff: [lorentzenchr/notebooks] Fix colsample_bynode (Issue #4) In the new blog post with codehttps://github.com/lorentzenchr/notebooks/blob/master/blogposts/2021-11-13%20random%20forests%20monotone.ipynbhttps://github.com/lorentzenchr/notebooks/blob/master/blogposts/2021-11-13%20random%20forests%20monotone.rthe formula for colsample_bynode might need correction.Python int(np.sqrt(m)) / m -> np.sqrt(m) // mR floor(sqrt(m)) / m -> floor(sqrt(m) / ***@***.*** ping—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mayer79** [comment]
Ich habs geändert. Etwas dumm, dass genau während dem Ändern die Beiträge auf r-blogger und python-blogger entstanden sind. So ist die einzige konsistente Version jene auf unserem Blog.  PS: nachher habe ich gemerkt, dass der ursprüngliche Code korrekt war: int(np.sqrt(m)) / m emuliert genau das Verhalten von «ranger»… aber da sqrt(m) tendenziell etwas schlechter als m/3 funktioniert, macht die Änderung trotzdem einigermassen Sinn. Gesendet von Mail für Windows Von: Michael MayerGesendet: Samstag, 13. November 2021 14:51An: lorentzenchr/notebooksBetreff: AW: [lorentzenchr/notebooks] Fix colsample_bynode (Issue #4) Ja, das ist etwas seltsam, danke. Ich setze den Wert auf 1/3 und aktualisiere alles. Gesendet von Mail für Windows Von: Christian LorentzenGesendet: Samstag, 13. November 2021 14:38An: lorentzenchr/notebooksCc: Michael Mayer; MentionBetreff: [lorentzenchr/notebooks] Fix colsample_bynode (Issue #4) In the new blog post with codehttps://github.com/lorentzenchr/notebooks/blob/master/blogposts/2021-11-13%20random%20forests%20monotone.ipynbhttps://github.com/lorentzenchr/notebooks/blob/master/blogposts/2021-11-13%20random%20forests%20monotone.rthe formula for colsample_bynode might need correction.Python int(np.sqrt(m)) / m -> np.sqrt(m) // mR floor(sqrt(m)) / m -> floor(sqrt(m) / ***@***.*** ping—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mayer79** [comment]
Done

**Comment by lorentzenchr** [comment]
Merci.
